export const FETCH_FILMS_REQUEST = 'FETCH_FILMS_REQUEST';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAILURE = 'FETCH_FILMS_FAILURE';

export const SET_SEARCH_KEY = 'SET_SEARCH_KEY';

export const FETCH_SEARCH_FILMS_REQUEST = 'FETCH_SEARCH_FILMS_REQUEST';
export const FETCH_SEARCH_FILMS_SUCCESS = 'FETCH_SEARCH_FILMS_SUCCESS';
export const FETCH_SEARCH_FILMS_FAILURE = 'FETCH_SEARCH_FILMS_FAILURE';

export const FETCH_ONE_FILM_REQUEST = 'FETCH_ONE_FILM_REQUEST';
export const FETCH_ONE_FILM_SUCCESS = 'FETCH_ONE_FILM_SUCCESS';
export const FETCH_ONE_FILM_FAILURE = 'FETCH_ONE_FILM_FAILURE';

export const DELETE_ONE_FILM_REQUEST = 'DELETE_ONE_FILM_REQUEST';
export const DELETE_ONE_FILM_SUCCESS = 'DELETE_ONE_FILM_SUCCESS';
export const DELETE_ONE_FILM_FAILURE = 'DELETE_ONE_FILM_FAILURE';

export const DELETE_ALL_FILMS_REQUEST = 'DELETE_ALL_FILMS_REQUEST';
export const DELETE_ALL_FILMS_SUCCESS = 'DELETE_ALL_FILMS_SUCCESS';
export const DELETE_ALL_FILMS_FAILURE = 'DELETE_ALL_FILMS_FAILURE';

export const ADD_ONE_FILM_REQUEST = 'ADD_ONE_FILM_REQUEST';
export const ADD_ONE_FILM_SUCCESS = 'ADD_ONE_FILM_SUCCESS';
export const ADD_ONE_FILM_FAILURE = 'ADD_ONE_FILM_FAILURE';

export const SEND_FILE_REQUEST = 'SEND_FILE_REQUEST';
export const SEND_FILE_SUCCESS = 'SEND_FILE_SUCCESS';
export const SEND_FILE_FAILURE = 'SEND_FILE_FAILURE';